
import React, { useState, useMemo, useEffect } from 'react';
import { Search, Filter, Activity, Zap, BarChart2, PieChart as PieIcon, TrendingUp, Layers, Hash, AlertTriangle, RefreshCw, X, Loader2 } from 'lucide-react';
import { NewsArticle } from '../types';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell, PieChart, Pie, Legend, LabelList, Sector } from 'recharts';

type TabType = 'all' | 'macro' | 'industry';
type QuickFilterType = 'none' | 'high_impact' | 'top_sector';
type ScoreFilterType = 'high' | 'medium' | 'low' | null;

// 自定义环形图的 Active Shape
const renderActiveShape = (props: any) => {
  const { cx, cy, innerRadius, outerRadius, startAngle, endAngle, fill, payload } = props;
  return (
    <g>
      <text x={cx} y={cy} dy={-10} textAnchor="middle" fill="#334155" fontWeight={700} fontSize={18}>
        {payload.value}条
      </text>
      <text x={cx} y={cy} dy={15} textAnchor="middle" fill="#94a3b8" fontSize={12}>
        {payload.name.split(' ')[0]}
      </text>
      <Sector
        cx={cx}
        cy={cy}
        innerRadius={innerRadius}
        outerRadius={outerRadius + 6}
        startAngle={startAngle}
        endAngle={endAngle}
        fill={fill}
      />
    </g>
  );
};

const NewsFeed: React.FC = () => {
  // Search State (Local Only)
  const [query, setQuery] = useState('');
  
  // Database Feed State
  const [activeTab, setActiveTab] = useState<TabType>('all');
  const [quickFilter, setQuickFilter] = useState<QuickFilterType>('none');
  const [scoreFilter, setScoreFilter] = useState<ScoreFilterType>(null);
  
  // Data Fetching State
  const [feedNews, setFeedNews] = useState<NewsArticle[]>([]);
  const [loading, setLoading] = useState(true);
  const [lastUpdated, setLastUpdated] = useState<string>('');

  // Fetch Data from shared JSON file (Generated by Python Backend)
  const fetchNewsData = async () => {
    try {
      // 在 Docker 环境中，Nginx 会将 backend 生成的 json 映射到 /data/news_data.json
      // 本地开发时，如果你没有运行 backend，这可能会 404
      const response = await fetch('/data/news_data.json');
      if (!response.ok) throw new Error("Data not found");
      
      const data = await response.json();
      setFeedNews(data);
      setLastUpdated(new Date().toLocaleTimeString());
    } catch (error) {
      console.warn("无法加载实时数据，使用演示数据 fallback", error);
      // Fallback mock data if backend is not running or file not found
      setFeedNews([
        {
            id: 'mock-1',
            title: '（演示数据）后端服务未连接：请启动 Docker Backend',
            content: '当前显示的是静态演示数据。请确保 docker-compose up 已运行，且 Python 脚本已成功抓取并写入 news_data.json。',
            url: '#',
            source: '系统提示',
            publishTime: '刚刚',
            score: 99,
            industry: '系统通知',
            aiReason: '系统自检提示'
        },
        // ... keep a few other mocks for layout checking
      ]);
    } finally {
      setLoading(false);
    }
  };

  // Initial Fetch and Polling
  useEffect(() => {
    fetchNewsData();
    const interval = setInterval(fetchNewsData, 30000); // Poll every 30 seconds
    return () => clearInterval(interval);
  }, []);

  // --- Statistics Calculation (Pre-filter) ---
  const globalStats = useMemo(() => {
     const total = feedNews.length;
     const highImpactCount = feedNews.filter(n => (n.score || 0) >= 80).length;
     const avgScore = total > 0 ? Math.round(feedNews.reduce((acc, cur) => acc + (cur.score || 0), 0) / total) : 0;
     
     // Calculate Top Sector
     const stats: Record<string, number> = {};
     feedNews.forEach(news => {
        if (news.industry && !news.industry.includes('宏观') && !news.industry.includes('系统')) { // Exclude macro and system
          const mainIndustry = news.industry.split('-')[0];
          stats[mainIndustry] = (stats[mainIndustry] || 0) + 1;
        }
     });
     const sortedSectors = Object.entries(stats).sort((a, b) => b[1] - a[1]);
     const topIndustry = sortedSectors.length > 0 ? sortedSectors[0][0] : '暂无';

     return { total, highImpactCount, avgScore, topIndustry };
  }, [feedNews]);


  // Filter logic
  const filteredNews = useMemo(() => {
    let filtered = feedNews;

    // 0. Apply Quick Filters from Top Cards
    if (quickFilter === 'high_impact') {
        filtered = filtered.filter(item => (item.score || 0) >= 80);
    } else if (quickFilter === 'top_sector') {
        filtered = filtered.filter(item => item.industry?.includes(globalStats.topIndustry));
    }

    // 0.5 Apply Score Filter from Pie Chart
    if (scoreFilter === 'high') filtered = filtered.filter(item => (item.score || 0) >= 80);
    if (scoreFilter === 'medium') filtered = filtered.filter(item => (item.score || 0) >= 50 && (item.score || 0) < 80);
    if (scoreFilter === 'low') filtered = filtered.filter(item => (item.score || 0) < 50);


    // 1. Category Filter (Tabs) - Only apply if no specific metric filter is active
    if (quickFilter === 'none' && scoreFilter === null) {
        switch (activeTab) {
        case 'macro':
            filtered = filtered.filter(item => 
            (item.industry?.includes('宏观') || item.industry?.includes('银行') || item.industry?.includes('非银')) && (item.score || 0) > 50
            );
            break;
        case 'industry':
            filtered = filtered.filter(item => 
            !item.industry?.includes('宏观') && (item.score || 0) >= 50
            );
            break;
        default:
            break;
        }
    }

    // 2. Text Search Filter (Always applies)
    if (query.trim()) {
      const q = query.toLowerCase();
      filtered = filtered.filter(item => 
        item.title.toLowerCase().includes(q) || 
        (item.content && item.content.toLowerCase().includes(q)) ||
        (item.industry && item.industry.toLowerCase().includes(q))
      );
    }

    // 3. Sort by Score desc
    return filtered.sort((a, b) => (b.score || 0) - (a.score || 0));
  }, [feedNews, query, activeTab, quickFilter, scoreFilter, globalStats.topIndustry]);

  // --- Statistics Calculation for Charts (Post-filter for Industry, Global for Score) ---

  // 1. Industry Frequency
  const industryStats = useMemo(() => {
    const stats: Record<string, number> = {};
    filteredNews.forEach(news => {
      if (news.industry) {
        if (news.industry.includes('宏观') || news.industry.includes('系统')) return;
        let mainIndustry = news.industry.split('-')[0];
        stats[mainIndustry] = (stats[mainIndustry] || 0) + 1;
      }
    });
    return Object.entries(stats)
      .map(([name, value]) => ({ name, value }))
      .sort((a, b) => b.value - a.value)
      .slice(0, 7);
  }, [filteredNews]);

  // 2. Score Distribution
  const scoreDistribution = useMemo(() => {
    let high = 0, medium = 0, low = 0;
    feedNews.forEach(n => {
      const s = n.score || 0;
      if (s >= 80) high++;
      else if (s >= 50) medium++;
      else low++;
    });
    return [
      { name: '重磅 (80+)', value: high, color: '#ef4444', type: 'high' },
      { name: '重要 (50-79)', value: medium, color: '#f59e0b', type: 'medium' },
      { name: '一般 (<50)', value: low, color: '#94a3b8', type: 'low' }
    ].filter(i => i.value > 0);
  }, [feedNews]);

  // Handle Card Clicks
  const handleCardClick = (type: QuickFilterType) => {
    setScoreFilter(null); // Reset pie filter
    if (quickFilter === type) {
        setQuickFilter('none'); 
    } else {
        setQuickFilter(type); 
        if (type !== 'none') setActiveTab('all');
    }
  };

  // Handle Chart Bar Click
  const handleIndustryClick = (data: any) => {
      if (data && data.name) {
          setQuery(data.name); 
      }
  };

  // Handle Pie Slice Click
  const handlePieClick = (data: any, index: number) => {
     const type = data.type as ScoreFilterType;
     setQuickFilter('none'); // Reset card filter
     if (scoreFilter === type) {
         setScoreFilter(null); // Toggle off
     } else {
         setScoreFilter(type);
         setActiveTab('all');
     }
  };

  const activePieIndex = useMemo(() => {
      if (!scoreFilter) return -1;
      return scoreDistribution.findIndex(item => item.type === scoreFilter);
  }, [scoreFilter, scoreDistribution]);

  return (
    <div className="flex flex-col space-y-6 animate-fade-in">
      
      {/* 1. Header & Title */}
      <div className="flex flex-col">
        <h2 className="text-2xl font-bold text-slate-800">实时新闻收集</h2>
      </div>

      {/* 2. Interactive Metrics Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {/* Total News */}
        <button 
            onClick={() => handleCardClick('none')}
            className={`p-4 rounded-xl border shadow-sm flex items-center space-x-4 transition-all duration-200 text-left ${
                quickFilter === 'none' && query === '' && scoreFilter === null
                ? 'bg-blue-50 border-blue-200 ring-2 ring-blue-100' 
                : 'bg-white border-slate-100 hover:bg-slate-50 hover:shadow-md'
            }`}
        >
          <div className={`p-3 rounded-lg ${quickFilter === 'none' ? 'bg-blue-100' : 'bg-blue-50'}`}>
            <Layers className={`w-6 h-6 ${quickFilter === 'none' ? 'text-blue-700' : 'text-blue-600'}`} />
          </div>
          <div>
            <p className="text-xs text-slate-500 font-medium uppercase">资讯总数</p>
            <p className="text-2xl font-bold text-slate-800">{globalStats.total}</p>
          </div>
          {quickFilter !== 'none' && <RefreshCw className="w-4 h-4 text-slate-400 ml-auto" />}
        </button>

        {/* High Impact News */}
        <button 
            onClick={() => handleCardClick('high_impact')}
            className={`p-4 rounded-xl border shadow-sm flex items-center space-x-4 transition-all duration-200 text-left ${
                quickFilter === 'high_impact'
                ? 'bg-red-50 border-red-200 ring-2 ring-red-100' 
                : 'bg-white border-slate-100 hover:bg-slate-50 hover:shadow-md'
            }`}
        >
          <div className={`p-3 rounded-lg ${quickFilter === 'high_impact' ? 'bg-red-100' : 'bg-red-50'}`}>
            <AlertTriangle className={`w-6 h-6 ${quickFilter === 'high_impact' ? 'text-red-700' : 'text-red-600'}`} />
          </div>
          <div>
            <p className="text-xs text-slate-500 font-medium uppercase">高价值新闻</p>
            <p className="text-2xl font-bold text-slate-800">{globalStats.highImpactCount}</p>
          </div>
        </button>

        {/* Top Sector */}
        <button 
            onClick={() => handleCardClick('top_sector')}
            className={`p-4 rounded-xl border shadow-sm flex items-center space-x-4 transition-all duration-200 text-left ${
                quickFilter === 'top_sector'
                ? 'bg-indigo-50 border-indigo-200 ring-2 ring-indigo-100' 
                : 'bg-white border-slate-100 hover:bg-slate-50 hover:shadow-md'
            }`}
        >
          <div className={`p-3 rounded-lg ${quickFilter === 'top_sector' ? 'bg-indigo-100' : 'bg-indigo-50'}`}>
            <Activity className={`w-6 h-6 ${quickFilter === 'top_sector' ? 'text-indigo-700' : 'text-indigo-600'}`} />
          </div>
          <div>
            <p className="text-xs text-slate-500 font-medium uppercase">最热板块</p>
            <p className="text-lg font-bold text-slate-800 truncate w-24" title={globalStats.topIndustry}>{globalStats.topIndustry}</p>
          </div>
        </button>

        {/* Average Score */}
        <div className="bg-white p-4 rounded-xl border border-slate-100 shadow-sm flex items-center space-x-4">
          <div className="p-3 bg-amber-50 rounded-lg">
            <BarChart2 className="w-6 h-6 text-amber-600" />
          </div>
          <div>
            <p className="text-xs text-slate-500 font-medium uppercase">平均强度</p>
            <p className="text-2xl font-bold text-slate-800">{globalStats.avgScore}</p>
          </div>
        </div>
      </div>

      {/* 3. Visualization Dashboard */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left Chart: Industry Heat */}
        <div className="lg:col-span-2 bg-white p-5 rounded-xl border border-slate-100 shadow-sm flex flex-col h-80">
          <h3 className="text-sm font-bold text-slate-700 mb-4 flex items-center">
            <Hash className="w-4 h-4 mr-2 text-slate-400" />
            行业热度排行 (Top Sectors) - <span className="text-xs font-normal text-slate-400 ml-1">点击条形图筛选</span>
          </h3>
          <div className="flex-1 w-full min-w-0">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart 
                layout="vertical" 
                data={industryStats} 
                margin={{ top: 5, right: 40, left: 40, bottom: 5 }}
              >
                <CartesianGrid strokeDasharray="3 3" horizontal={false} vertical={true} stroke="#f1f5f9" />
                <XAxis type="number" hide />
                <YAxis dataKey="name" type="category" width={100} tick={{fontSize: 12, fill: '#64748b'}} axisLine={false} tickLine={false} />
                <Bar 
                  dataKey="value" 
                  barSize={20} 
                  radius={[0, 4, 4, 0]} 
                  onClick={handleIndustryClick}
                  cursor="pointer"
                >
                  {industryStats.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={index < 3 ? '#3b82f6' : '#94a3b8'} />
                  ))}
                  <LabelList dataKey="value" position="right" fill="#64748b" fontSize={12} fontWeight="bold" />
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Right Chart: Score Distribution */}
        <div className="bg-white p-5 rounded-xl border border-slate-100 shadow-sm flex flex-col h-80">
          <h3 className="text-sm font-bold text-slate-700 mb-1 flex items-center justify-between">
            <div className="flex items-center">
                <Zap className="w-4 h-4 mr-2 text-slate-400" />
                <span>资讯价值分布</span>
            </div>
            <span className="text-xs font-normal text-slate-400">点击色块筛选</span>
          </h3>
          <div className="flex-1 relative flex flex-col items-center justify-center">
            <div className="w-full flex-1">
                <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                    <Pie
                        data={scoreDistribution}
                        cx="50%"
                        cy="50%"
                        innerRadius={60}
                        outerRadius={80}
                        paddingAngle={5}
                        dataKey="value"
                        onClick={handlePieClick}
                        {...({ activeIndex: activePieIndex } as any)}
                        activeShape={renderActiveShape}
                        cursor="pointer"
                    >
                    {scoreDistribution.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={entry.color} stroke="none" className="transition-all duration-300 hover:opacity-80" />
                    ))}
                    </Pie>
                    <Tooltip 
                        formatter={(value: number) => [`${value} 条`, '数量']}
                        contentStyle={{borderRadius: '8px'}} 
                    />
                    <Legend 
                        layout="vertical" 
                        verticalAlign="middle" 
                        align="right"
                        iconType="circle" 
                        iconSize={8}
                        wrapperStyle={{fontSize: '12px', color: '#64748b'}}
                    />
                </PieChart>
                </ResponsiveContainer>
            </div>
            <div className="mt-2 text-center">
                <span className="text-sm font-medium text-slate-600">监测总数：<span className="font-bold text-slate-800">{feedNews.length}</span> 条</span>
            </div>
          </div>
        </div>
      </div>

      {/* 4. Control Bar */}
      <div className="sticky top-0 z-10 bg-slate-50 pt-2 pb-4">
        <div className="flex flex-col md:flex-row md:items-center justify-between space-y-4 md:space-y-0">
          
          {/* Left: Tabs & Search */}
          <div className="flex flex-col md:flex-row md:items-center space-y-3 md:space-y-0 md:space-x-4 flex-1">
             {/* Tabs */}
             <div className={`bg-white p-1 rounded-lg border border-slate-200 shadow-sm inline-flex self-start transition-opacity ${quickFilter !== 'none' || scoreFilter !== null ? 'opacity-50 pointer-events-none' : 'opacity-100'}`}>
              {[
                { id: 'all', label: '全部实时资讯' },
                { id: 'macro', label: '重点宏观新闻' },
                { id: 'industry', label: '重点行业新闻' },
              ].map((tab) => (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id as TabType)}
                  className={`px-4 py-2 text-sm font-medium rounded-md transition-all ${
                    activeTab === tab.id
                      ? 'bg-blue-600 text-white shadow-md'
                      : 'text-slate-500 hover:text-slate-700 hover:bg-slate-50'
                  }`}
                >
                  {tab.label}
                </button>
              ))}
            </div>

            {/* Filter Indicators */}
            {(quickFilter !== 'none' || scoreFilter !== null) && (
                <div className="flex items-center space-x-2">
                    {quickFilter !== 'none' && (
                        <div className="flex items-center bg-blue-100 text-blue-700 px-3 py-1.5 rounded-lg text-sm font-medium animate-pulse">
                            <span>已筛选：{quickFilter === 'high_impact' ? '高价值新闻' : `板块: ${globalStats.topIndustry}`}</span>
                            <button onClick={() => setQuickFilter('none')} className="ml-2 hover:text-blue-900"><X className="w-4 h-4"/></button>
                        </div>
                    )}
                    {scoreFilter !== null && (
                        <div className={`flex items-center px-3 py-1.5 rounded-lg text-sm font-medium animate-pulse ${
                            scoreFilter === 'high' ? 'bg-red-100 text-red-700' : 
                            scoreFilter === 'medium' ? 'bg-amber-100 text-amber-800' : 'bg-slate-200 text-slate-700'
                        }`}>
                            <span>分值筛选：{scoreFilter === 'high' ? '重磅 (80+)' : scoreFilter === 'medium' ? '重要 (50-79)' : '一般 (<50)'}</span>
                            <button onClick={() => setScoreFilter(null)} className="ml-2 opacity-70 hover:opacity-100"><X className="w-4 h-4"/></button>
                        </div>
                    )}
                </div>
            )}

            {/* Local Search */}
            <div className="relative group w-full md:w-64 ml-auto md:ml-4">
              <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                <Search className="h-4 w-4 text-slate-400 group-focus-within:text-blue-500 transition-colors" />
              </div>
              <input
                type="text"
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                className="block w-full pl-10 pr-3 py-2.5 border border-slate-200 rounded-lg leading-5 bg-white placeholder-slate-400 focus:outline-none focus:bg-white focus:ring-2 focus:ring-blue-100 focus:border-blue-400 sm:text-sm transition-all shadow-sm"
                placeholder="本地搜索：标题 / 行业 / 内容..."
              />
            </div>
          </div>

          {/* Right: System Monitor */}
          <div className="flex items-center space-x-2 bg-white px-3 py-2 rounded-full border border-slate-200 shadow-sm">
             <div className="flex items-center space-x-1.5 px-2 border-r border-slate-100">
               <div className={`w-2 h-2 rounded-full animate-pulse ${loading ? 'bg-amber-500' : 'bg-emerald-500'}`}></div>
               <span className="text-xs font-medium text-slate-600">Docker {loading ? 'Syncing' : 'Active'}</span>
             </div>
             <div className="flex items-center space-x-1.5 px-2">
               <span className="text-xs font-medium text-slate-400">上次更新: {lastUpdated || 'N/A'}</span>
             </div>
          </div>
        </div>
      </div>

      {/* 5. News List */}
      <div className="grid gap-4">
        {loading && filteredNews.length === 0 ? (
          <div className="text-center py-20">
             <Loader2 className="w-8 h-8 text-blue-500 animate-spin mx-auto" />
             <p className="text-slate-500 mt-2">正在从 Docker Backend 读取数据...</p>
          </div>
        ) : (
            filteredNews.length > 0 ? (
            filteredNews.map((news) => (
                <div 
                key={news.id} 
                className="bg-white p-5 rounded-xl border border-slate-100 shadow-sm hover:shadow-md transition-all duration-200 group relative overflow-hidden"
                >
                <div 
                    className={`absolute left-0 top-0 bottom-0 w-1 ${
                    (news.score || 0) >= 80 ? 'bg-red-500' : (news.score || 0) >= 50 ? 'bg-amber-500' : 'bg-slate-300'
                    }`} 
                />

                <div className="flex justify-between items-start mb-2 pl-3">
                    <div className="flex items-center space-x-2 mb-1">
                    {news.industry && (
                        <span className="bg-slate-100 text-slate-600 text-xs px-2 py-0.5 rounded-md font-medium border border-slate-200">
                        {news.industry}
                        </span>
                    )}
                    <span className={`text-xs px-2 py-0.5 rounded-md font-medium border ${
                        news.source === '财联社' 
                        ? 'bg-red-50 text-red-600 border-red-100' 
                        : 'bg-orange-50 text-orange-600 border-orange-100'
                    }`}>
                        {news.source}
                    </span>
                    <span className="text-xs text-slate-400">{news.publishTime}</span>
                    </div>
                    
                    <div className="flex items-center space-x-2">
                    {news.score !== undefined && (
                        <div className={`flex items-center space-x-1 px-2 py-1 rounded-full ${
                        news.score >= 80 ? 'bg-red-50 text-red-700' : news.score >= 50 ? 'bg-amber-50 text-amber-700' : 'bg-slate-50 text-slate-600'
                        }`}>
                        <Activity className="w-3 h-3" />
                        <span className="text-xs font-bold">{news.score}</span>
                        </div>
                    )}
                    </div>
                </div>

                <div className="pl-3">
                    <h3 className="text-lg font-bold text-slate-800 mb-2 group-hover:text-blue-700 transition-colors">
                    {news.title}
                    </h3>
                    <p className="text-sm text-slate-500 leading-relaxed line-clamp-2 mb-3">
                    {news.content}
                    </p>

                    {news.aiReason && (
                    <div className="bg-slate-50 rounded-lg p-3 border border-slate-100 flex items-start space-x-2">
                        <Zap className="w-4 h-4 text-indigo-500 mt-0.5 flex-shrink-0" />
                        <p className="text-xs text-slate-700">
                        <span className="font-semibold text-indigo-700">AI 点评：</span>
                        {news.aiReason}
                        </p>
                    </div>
                    )}
                </div>
                </div>
            ))
            ) : (
            <div className="text-center py-20 bg-white rounded-xl border border-slate-100 border-dashed">
                <div className="mx-auto w-16 h-16 bg-slate-50 rounded-full flex items-center justify-center mb-4">
                <Filter className="w-8 h-8 text-slate-300" />
                </div>
                <p className="text-slate-500 font-medium">没有找到匹配的新闻</p>
                <p className="text-slate-400 text-sm mt-1">尝试切换筛选条件或更换搜索词</p>
            </div>
            )
        )}
      </div>
    </div>
  );
};

export default NewsFeed;
