import React, { useState, useMemo, useEffect } from 'react';
import { Search, Filter, Activity, Zap, BarChart2, PieChart as PieIcon, TrendingUp, Layers, Hash, AlertTriangle, RefreshCw, X, Loader2 } from 'lucide-react';
import { NewsArticle } from '../types';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell, PieChart, Pie, Legend, LabelList, Sector } from 'recharts';

type TabType = 'all' | 'macro' | 'industry';
type QuickFilterType = 'none' | 'high_impact' | 'top_sector';
type ScoreFilterType = 'high' | 'medium' | 'low' | null;

// 自定义环形图的 Active Shape
const renderActiveShape = (props: any) => {
  const { cx, cy, innerRadius, outerRadius, startAngle, endAngle, fill, payload } = props;
  return (
    <g>
      <text x={cx} y={cy} dy={-10} textAnchor="middle" fill="#334155" fontWeight={700} fontSize={18}>
        {payload.value}条
      </text>
      <text x={cx} y={cy} dy={15} textAnchor="middle" fill="#94a3b8" fontSize={12}>
        {payload.name.split(' ')[0]}
      </text>
      <Sector
        cx={cx}
        cy={cy}
        innerRadius={innerRadius}
        outerRadius={outerRadius + 6}
        startAngle={startAngle}
        endAngle={endAngle}
        fill={fill}
      />
    </g>
  );
};

// 安全地把 publishTime 转成时间戳（失败就返回 0）
const parseTime = (t?: string) => {
  if (!t) return 0;
  // 过滤 “刚刚” 这种 mock 文本
  if (t === '刚刚') return 0;
  const d = new Date(t);
  const ts = d.getTime();
  return Number.isNaN(ts) ? 0 : ts;
};

const NewsFeed: React.FC = () => {
  // Search State (Local Only)
  const [query, setQuery] = useState('');
  
  // Database Feed State
  const [activeTab, setActiveTab] = useState<TabType>('all');
  const [quickFilter, setQuickFilter] = useState<QuickFilterType>('none');
  const [scoreFilter, setScoreFilter] = useState<ScoreFilterType>(null);
  
  // Data Fetching State
  const [feedNews, setFeedNews] = useState<NewsArticle[]>([]);
  const [loading, setLoading] = useState(true);
  const [lastUpdated, setLastUpdated] = useState<string>('');

  // Fetch Data from shared JSON file (Generated by Python Backend)
  const fetchNewsData = async () => {
    try {
      // 在 Docker 环境中，Nginx 会将 backend 生成的 json 映射到 /data/news_data.json
      const response = await fetch('/data/news_data.json');
      if (!response.ok) throw new Error("Data not found");
      
      const data = await response.json();
      setFeedNews(data);
      setLastUpdated(new Date().toLocaleTimeString());
    } catch (error) {
      console.warn("无法加载实时数据，使用演示数据 fallback", error);
      // Fallback mock data if backend is not running or file not found
      setFeedNews([
        {
          id: 'mock-1',
          title: '（演示数据）后端服务未连接：请启动 Docker Backend',
          content: '当前显示的是静态演示数据。请确保 docker-compose up 已运行，且 Python 脚本已成功抓取并写入 news_data.json。',
          url: '#',
          source: '系统提示',
          publishTime: '刚刚',
          score: 99,
          industry: '系统通知',
          aiReason: '系统自检提示'
        },
      ]);
    } finally {
      setLoading(false);
    }
  };

  // Initial Fetch and Polling
  useEffect(() => {
    fetchNewsData();
    const interval = setInterval(fetchNewsData, 30000); // Poll every 30 seconds
    return () => clearInterval(interval);
  }, []);

  // --- Statistics Calculation (Pre-filter) ---
  const globalStats = useMemo(() => {
    const total = feedNews.length;
    const highImpactCount = feedNews.filter(n => (n.score || 0) >= 80).length;
    const avgScore = total > 0 ? Math.round(feedNews.reduce((acc, cur) => acc + (cur.score || 0), 0) / total) : 0;
    
    // Calculate Top Sector
    const stats: Record<string, number> = {};
    feedNews.forEach(news => {
      if (news.industry && !news.industry.includes('宏观') && !news.industry.includes('系统')) { // Exclude macro and system
        const mainIndustry = news.industry.split('-')[0];
        stats[mainIndustry] = (stats[mainIndustry] || 0) + 1;
      }
    });
    const sortedSectors = Object.entries(stats).sort((a, b) => b[1] - a[1]);
    const topIndustry = sortedSectors.length > 0 ? sortedSectors[0][0] : '暂无';

    return { total, highImpactCount, avgScore, topIndustry };
  }, [feedNews]);

  // Filter logic
  const filteredNews = useMemo(() => {
    let filtered = feedNews;

    // 0. Apply Quick Filters from Top Cards
    if (quickFilter === 'high_impact') {
      filtered = filtered.filter(item => (item.score || 0) >= 80);
    } else if (quickFilter === 'top_sector') {
      filtered = filtered.filter(item => item.industry?.includes(globalStats.topIndustry));
    }

    // 0.5 Apply Score Filter from Pie Chart
    if (scoreFilter === 'high') filtered = filtered.filter(item => (item.score || 0) >= 80);
    if (scoreFilter === 'medium') filtered = filtered.filter(item => (item.score || 0) >= 50 && (item.score || 0) < 80);
    if (scoreFilter === 'low') filtered = filtered.filter(item => (item.score || 0) < 50);

    // 1. Category Filter (Tabs) - Only apply if no specific metric filter is active
    if (quickFilter === 'none' && scoreFilter === null) {
      switch (activeTab) {
        case 'macro':
          filtered = filtered.filter(item => 
            (item.industry?.includes('宏观') || item.industry?.includes('银行') || item.industry?.includes('非银')) && (item.score || 0) > 50
          );
          break;
        case 'industry':
          filtered = filtered.filter(item => 
            !item.industry?.includes('宏观') && (item.score || 0) >= 50
          );
          break;
        default:
          break;
      }
    }

    // 2. Text Search Filter (Always applies)
    if (query.trim()) {
      const q = query.toLowerCase();
      filtered = filtered.filter(item => 
        item.title.toLowerCase().includes(q) || 
        (item.content && item.content.toLowerCase().includes(q)) ||
        (item.industry && item.industry.toLowerCase().includes(q))
      );
    }

    // 3. 排序逻辑：优先按时间（新→旧），同一时间再按分数（高→低）
    return [...filtered].sort((a, b) => {
      const tb = parseTime(b.publishTime);
      const ta = parseTime(a.publishTime);
      if (tb !== ta) {
        return tb - ta;  // 时间新的在前
      }
      return (b.score || 0) - (a.score || 0); // 分数高的在前
    });
  }, [feedNews, query, activeTab, quickFilter, scoreFilter, globalStats.topIndustry]);

  // --- Statistics Calculation for Charts (Post-filter for Industry, Global for Score) ---

  // 1. Industry Frequency
  const industryStats = useMemo(() => {
    const stats: Record<string, number> = {};
    filteredNews.forEach(news => {
      if (news.industry) {
        if (news.industry.includes('宏观') || news.industry.includes('系统')) return;
        let mainIndustry = news.industry.split('-')[0];
        stats[mainIndustry] = (stats[mainIndustry] || 0) + 1;
      }
    });
    return Object.entries(stats)
      .map(([name, value]) => ({ name, value }))
      .sort((a, b) => b.value - a.value)
      .slice(0, 7);
  }, [filteredNews]);

  // 2. Score Distribution
  const scoreDistribution = useMemo(() => {
    let high = 0, medium = 0, low = 0;
    feedNews.forEach(n => {
      const s = n.score || 0;
      if (s >= 80) high++;
      else if (s >= 50) medium++;
      else low++;
    });
    return [
      { name: '重磅 (80+)', value: high, color: '#ef4444', type: 'high' },
      { name: '重要 (50-79)', value: medium, color: '#f59e0b', type: 'medium' },
      { name: '一般 (<50)', value: low, color: '#94a3b8', type: 'low' }
    ].filter(i => i.value > 0);
  }, [feedNews]);

  // Handle Card Clicks
  const handleCardClick = (type: QuickFilterType) => {
    setScoreFilter(null); // Reset pie filter
    if (quickFilter === type) {
      setQuickFilter('none'); 
    } else {
      setQuickFilter(type); 
      if (type !== 'none') setActiveTab('all');
    }
  };

  // Handle Chart Bar Click
  const handleIndustryClick = (data: any) => {
    if (data && data.name) {
      setQuery(data.name); 
    }
  };

  // Handle Pie Slice Click
  const handlePieClick = (data: any) => {
    const type = data.type as ScoreFilterType;
    setQuickFilter('none'); // Reset card filter
    if (scoreFilter === type) {
      setScoreFilter(null); // Toggle off
    } else {
      setScoreFilter(type);
      setActiveTab('all');
    }
  };

  const activePieIndex = useMemo(() => {
    if (!scoreFilter) return -1;
    return scoreDistribution.findIndex(item => item.type === scoreFilter);
  }, [scoreFilter, scoreDistribution]);

  return (
    <div className="flex flex-col space-y-6 animate-fade-in">
      {/* 1. Header & Title */}
      <div className="flex flex-col">
        <h2 className="text-2xl font-bold text-slate-800">实时新闻收集</h2>
      </div>

      {/* 2. Interactive Metrics Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {/* Total News */}
        <button 
          onClick={() => handleCardClick('none')}
          className={`p-4 rounded-xl border shadow-sm flex items-center space-x-4 transition-all duration-200 text-left ${
            quickFilter === 'none' && query === '' && scoreFilter === null
              ? 'bg-blue-50 border-blue-200 ring-2 ring-blue-100' 
              : 'bg-white border-slate-100 hover:bg-slate-50 hover:shadow-md'
          }`}
        >
          <div className={`p-3 rounded-lg ${quickFilter === 'none' ? 'bg-blue-100' : 'bg-blue-50'}`}>
            <Layers className={`w-6 h-6 ${quickFilter === 'none' ? 'text-blue-700' : 'text-blue-600'}`} />
          </div>
          <div>
            <p className="text-xs text-slate-500 font-medium uppercase">资讯总数</p>
            <p className="text-2xl font-bold text-slate-800">{globalStats.total}</p>
          </div>
          {quickFilter !== 'none' && <RefreshCw className="w-4 h-4 text-slate-400 ml-auto" />}
        </button>

        {/* High Impact News */}
        <button 
          onClick={() => handleCardClick('high_impact')}
          className={`p-4 rounded-xl border shadow-sm flex items-center space-x-4 transition-all duration-200 text-left ${
            quickFilter === 'high_impact'
              ? 'bg-red-50 border-red-200 ring-2 ring-red-100' 
              : 'bg-white border-slate-100 hover:bg-slate-50 hover:shadow-md'
          }`}
        >
          <div className={`p-3 rounded-lg ${quickFilter === 'high_impact' ? 'bg-red-100' : 'bg-red-50'}`}>
            <AlertTriangle className={`w-6 h-6 ${quickFilter === 'high_impact' ? 'text-red-700' : 'text-red-600'}`} />
          </div>
          <div>
            <p className="text-xs text-slate-500 font-medium uppercase">高价值新闻</p>
            <p className="text-2xl font-bold text-slate-800">{globalStats.highImpactCount}</p>
          </div>
        </button>

        {/* Top Sector */}
        <button 
          onClick={() => handleCardClick('top_sector')}
          className={`p-4 rounded-xl border shadow-sm flex items-center space-x-4 transition-all duration-200 text-left ${
            quickFilter === 'top_sector'
              ? 'bg-indigo-50 border-indigo-200 ring-2 ring-indigo-100' 
              : 'bg-white border-slate-100 hover:bg-slate-50 hover:shadow-md'
          }`}
        >
          <div className={`p-3 rounded-lg ${quickFilter === 'top_sector' ? 'bg-indigo-100' : 'bg-indigo-50'}`}>
            <Activity className={`w-6 h-6 ${quickFilter === 'top_sector' ? 'text-indigo-700' : 'text
